import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext, useEffect } from 'react';
import { UserContext, AppContext } from 'src/context/';
import styles from 'src/styles/Home.module.scss';
import { Button, ConnectCard } from '../src/components';
import { ONBOARDING_STATUSES } from 'src/constants/';

const Home: NextPage = () => {
  const router = useRouter();
  const {
    activateConfetti,
    onboardingStatus,
    setOnboardingStatus,
    isConnected,
    setIsConnected,
  } = useContext(AppContext);
  const { setWalletAddress } = useContext(UserContext);
  // useEffect(() => {
  //   // if (isConnected) {
  //   //   setTimeout(() => {
  //   //     router.push('/view');
  //   //   }, 2000);
  //   // }
  // });

  useEffect(() => {
    const savedWalletAddress = localStorage.getItem('walletAddress');
    const userOnboardingStatus = localStorage.getItem('onboardingStatus');
    const userAlreadyConnected = localStorage.getItem('isConnected');
    console.log({
      savedWalletAddress,
      userOnboardingStatus,
      userAlreadyConnected,
    });
    if (savedWalletAddress) setWalletAddress(savedWalletAddress);
    if (userAlreadyConnected) setIsConnected(true);
    if (userOnboardingStatus) {
      setOnboardingStatus(ONBOARDING_STATUSES['Done']);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Viewer App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ConnectCard />
      </main>
    </div>
  );
};

export default Home;
