import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import styles from 'src/styles/Home.module.scss'
import {Button,Canvas,Navbar,ConnectCard} from '../src/components';
import confettiObject from '../src/utils/confetti';
import {AppContextProvider} from 'src/context/App';
const Home: NextPage = () => {
  const printSomething = () => {
    // console.log(MetamaskInstance)
    confettiObject.startConfettiInner();
    setTimeout(() => {
      confettiObject.stopConfettiInner();
    }, 3*1000);
  }
  
  return (
    <AppContextProvider>
<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Canvas/>
      {/* <Script src="../src/components/core/confetti-falling-animation/confetti.js" strategy="lazyOnload" /> */}
      <main className={styles.main}>
        <ConnectCard/>
        <Button triggerOnClick={printSomething}> asbxsaxha</Button>
  
      </main>
    </div>
    </AppContextProvider>
    
  )
}

export default Home
