import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router'
import {useContext,useEffect} from 'react';
import {AppContext} from "src/context/";
import styles from 'src/styles/Home.module.scss'
import {Button,Navbar,NftCard} from '../src/components';
import { GalleryGrid } from '/src/layout/';
import axiosInstance from '/src/utils/axios';
import NftSDKInstance from '/src/services//NftSdk';
const Home: NextPage = () => {
  const {activateConfetti,isConnected,walletAddress,activeChain
} = useContext(AppContext);
  const router = useRouter();
  useEffect(() => {
    if(!isConnected) router.replace('/');
    NftSDKInstance.getWalletCollections(walletAddress,activeChain).then(console.log)
  },[]);
  return (
<div className={styles.container}>
      <Head>
        <title>NFT's  Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <GalleryGrid>
        <NftCard/>
        <NftCard/>
        <NftCard/>
        <NftCard/>
        <NftCard/>
        <NftCard/>
        </GalleryGrid>
      </main>
    </div>
    
  )
}

export default Home
