import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router'
import {useContext,useEffect} from 'react';
import {AppContext} from "src/context/";
import styles from 'src/styles/Home.module.scss'
import {Button,Navbar,ConnectCard} from '../src/components';

const Home: NextPage = () => {
  const {activateConfetti,isConnected} = useContext(AppContext);
  const router = useRouter();
  useEffect(() => {
    if(!isConnected) router.push('/');
  },[]);
  return (
<div className={styles.container}>
      <Head>
        <title>NFT's  Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        
      </main>
    </div>
    
  )
}

export default Home
